### PR TITLE
added merge sort

### PR DESCRIPTION
**Pull request by Shyam-2001**

### CODE REVIEW

**Review by edusanketdk — CHANGES_REQUESTED** [review]
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

**Comment by Shyam-2001** [comment]
done

**Review by Aman22sharma — APPROVED** [review]

**Comment by Aman22sharma** [comment]
Thank you for your contribution

**Pull request merged**
