### PR TITLE
Added BubbleSort in Python to the list

### PR DESCRIPTION
**Pull request by debajyoti22**

### CODE REVIEW

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

**Comment by debajyoti22** [comment]
Hi @Aman22sharma  have made the necessary changes . Please accept my PR

**Review by Aman22sharma — APPROVED** [review]

**Comment by Aman22sharma** [comment]
Thank you for your contribution

**Comment by debajyoti22** [comment]
Thank you !!

**Pull request merged**
