### PR TITLE
Create Stacks_priyanshu-28.py

### PR DESCRIPTION
**Pull request by priyanshu-28**
Implemented Stack

### CODE REVIEW

**Comment by priyanshu-28** [comment]
please consider for hacktober Fest

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

**Comment by priyanshu-28** [comment]
> Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

please check now, I hope I have done it right 👍🏻

**Review by Aman22sharma — APPROVED** [review]

**Comment by Aman22sharma** [comment]
Thanks for your contribution

**Pull request merged**
